Added RISC-V CHERI crossbuild changes

diff --git a/auto/feature b/auto/feature
--- a/auto/feature
+++ b/auto/feature
@@ -52,8 +52,14 @@ if [ -x $NGX_AUTOTEST ]; then
     case "$ngx_feature_run" in
 
         yes)
+	    if test -n "$NGX_CROSSCOMPILING"; then
+                echo " found (cross compiling so cannot run)"
+                ngx_found=yes
+                if test -n "$ngx_feature_name"; then
+                    have=$ngx_have_feature . auto/have
+                fi
             # /bin/sh is used to intercept "Killed" or "Abort trap" messages
-            if /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
+            elif  /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
                 echo " found"
                 ngx_found=yes
 
@@ -62,11 +68,17 @@ if [ -x $NGX_AUTOTEST ]; then
                 fi
 
             else
-                echo " found but is not working"
+		#file $NGX_AUTOTEST
+                #echo $NGX_AUTOCONF_ERR
+		echo " found but is not working"
             fi
         ;;
 
         value)
+	    if test -n "$NGX_CROSSCOMPILING"; then
+                echo " Cannot check due to cross compiling!"
+                exit 1
+            fi
             # /bin/sh is used to intercept "Killed" or "Abort trap" messages
             if /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
                 echo " found"
@@ -85,6 +97,10 @@ END
         ;;
 
         bug)
+	    if test -n "$NGX_CROSSCOMPILING"; then
+                echo " Cannot check due to cross compiling!"
+                exit 1
+            fi
             # /bin/sh is used to intercept "Killed" or "Abort trap" messages
             if /bin/sh -c $NGX_AUTOTEST >> $NGX_AUTOCONF_ERR 2>&1; then
                 echo " not found"
